language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - "pip install pipenv"
  - "pipenv install"

script:
  - "pipenv run pytest"
  - "pipenv run python analysis/analysis_strength.py"
